---
title: "About"
author: "John Morse"
date: "4/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

***

### Personal Information

Email: jmorse@hsph.harvard.edu

Github Repo: <https://github.com/jrmorse/prep_cost_effectiveness>

GitHub Profile: <https://github.com/jrmorse>

This webapp is the final project for the Harvard Gov1005 course. Please feel free to reach out with any comments or questions.

***

### Raw Data

With this project, I have aggregrated data from diverse sources including
the CDC, Rollins School of Public Health with Gilead Sciences, and various academic
papers presented by the National Center for Biotechnology Information.

All of my statistics regarding HIV and STI rates were taken directly from the CDC. Cost estimations of diseases were taken from academic journals as were the racial estimations for PrEP users. As PrEP is relatively new, there are no official statistics on the actual demography of its' users. This is a limitation of my work.

***

### Process

The first work I did was to scrape academic journals in order to gather cost estimates for HIV and STIs. The information here is from a highly cited paper that estimates both direct and indirect costs of various illnesses. The referenced paper can be found here: <https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2426671/>. This data is from 2006, so I adjusted the value of inflation to convey 2020 USD. 

After handling the costs, I set about loading statistics on the rates of HIV and STIs. To begin, I loaded data relating to PrEP usage. This information was set forth by Gilead with Rollins School of Public health and can be found here <https://aidsvu.org/> as as in my repo. Once I loaded and cleaned this data, I scraped another academic journal in order to gauge the estimated racial demographics of users. The paper I used can be accessed here: <https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6193685/>. 

Once this information was in R, I followed a similar process to load statistics to account for HIV and STI rates mostly beginning in 2012. These datasets came directly from a CDC platform called AtlasPlus. This website can be found here: <https://www.cdc.gov/nchhstp/atlas/index.htm> as well as in my repo. 

With all this data cleaned and matched appropriately, I was able to begin the process of creating graphs and interactive tools on the Shiny app.

***

### Limitations
