---
title: "about"
author: "John Morse"
date: "2/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Link to data: https://github.com/jrmorse/final_project_datasets/blob/master/datasets.Rmd


About: 
Since the HIV/AIDS epidemic first began in 1981, amazing, albeit slow, progress
has been made in the treatment and management of the disease in the United
States. Public Health campaigns combined with powerful pharmaceutical
innovations have played a pivotal role in changing the perception of the
diagnosis of HIV from a death sentence to that of a chronic condition. In 2012,
the United States witnessed the approval of a new drug that was able to prevent
the onset of HIV for at risk individuals. With, Pre-Exposure Prophylaxis (PrEP)
medication, high risk individuals have been able to live without contracting
HIV, thus saving millions of dollars each year for the U.S. healthcare system.
Accompanying this progress, however, is a spike in the prevalence of many other
sexually transmitted illnesses (STIs). With this increase in STI prevalence,
financial resources must be directed towards treatment. In my study, I aim to
link the advent of PrEP in the United States to this increased observation of
STIs, before discerning the cost efficiency of PrEP and its’ impact on the
United States’ healthcare system.

With this project, I have aggregrated data from diverse sources including
the CDC, Rollins School of Public Health with Gilead Sciences, and academic
research presented by the National Center for Biotechnology Information.

From the first look at the data, it
is clear that the rates of HIV have been decreasing while the rates of other STIs (notably, Chlamydia, Syphillis, and Gonorrhea) have increased.

Additionally, I have pulled in data regarding the estimated costs for all STIs
which include the direct medical costs of HIV. With this information, we can see
if the decreased numbers of HIV has saved the U.S. healthcare money, or if the
extra resources devoted towards STI treatment has surpassed any potential
savings. This type of analysis  will make it possible to consider if PrEP has
been a financially effective treatment in the eyes of the U.S. health system.

Next steps: 
1. Creating a column in the table of estimated medical costs for
STIs to convert the values of 2006USD to that of 2020 USD 
2. Rename columns in
the tables so that it is obvious from which dataset they come from (relevant for
step 3). 
3. Join all tables on the year variable. 
4. Remove columns that will
not be used in the analysis.