---
title: "datasets"
author: "John Morse"
date: "2/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(janitor)
library(tidyverse)
library(gt)
library(rvest)
library(reprex)
```

```{r}
# This includes the direct medical costs associated with key STIs in the U.S.. I
# will be looking at the costs of HIV, chlamydia, gonorrhea, and I think
# syphilis as well. The prices listed are in 2006 USD, so I will create another
# column that calculates the 2019 USD cost for each infection.I have used the
# pivot long function to create a new column relating to sex. The data should be
# clean and I have used the slice function to get rid of unwanted rows. I am
# confused as to how to make the cost column numeric. Don't I need to get rid
# of special characters.

table_costs_messy <- read_html("https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2426671/")%>% 
  html_node("table") %>% 
  html_table(header = TRUE) %>% 
  clean_names() %>% 
  slice(-1) %>% 
  slice(4:17)

# I've scraped a table and cleaned it, and have tried to remove special
# characters from two collumns so that I will be able to convert those values to
# integers later. This part of the code does not throw error messages.

costs_clean <- table_costs_messy %>% 
  rename(xF = value_applied, xM = x) %>% 
  pivot_longer(
    cols = starts_with("x"),
    names_to = "Sex",
    names_prefix = "x",
    values_to = "Cost",
    values_drop_na = FALSE
  ) %>% 
  mutate(Cost_2006 = parse_number(Cost)) %>% 
  mutate(Cost_2020 = (Cost_2006 * 1.31)) %>% 
  
# I did this line below to get rid of extra text in the parameter column.
  
  mutate_all(~ gsub(x =., pattern = "\\*| \\[5]| \\[6]| \\[1,64,65]| \\[85]", "")) %>% 
  select("parameter", "Sex", "Cost_2020")

costs_clean

```
```{r}
direct_costs <-
  costs_clean %>% 
  slice(1:10)
direct_costs
```

```{r}
indirect_costs_hiv <- costs_clean %>% 
  slice(13:14)
indirect_costs_hiv
```

```{r}
indirect_costs_sti <- costs_clean %>% 
  slice(21:28)
indirect_costs_sti
```
```{r}
# I now need to do a join of indirect costs sti and hiv with direct costs. 
```


```{r}
# Empty data set where I will store the files once they'e loaded in.
prep_data_1 <- data.frame()

# Listing out all the files in this particular folder. All of this data relates
# to PrEP usage in the U.S..
list <- list.files("Data_Sets/PrEP_Data")

# Here I have the actual function which is picking up on every document that
# ends in ".xlsx" in the "PrEP_Data" folder. The function reads in all of the
# data, and then spits each one into the empty dataframe that I have created.
# Each row is appended onto the preceding year's data.

listxlsx <- dir(pattern = "*.xlsx")
for (i in 1:length(list)){
  print(list[i])
  temp_data <- read_xlsx(paste("Data_Sets/PrEP_Data/",
                               list[i], sep = ""),
                         skip = 1) %>% 
    clean_names()
  
  prep_data_1 = rbind(prep_data_1, temp_data)
}

prep_data_1 <- prep_data_1 %>% 
  gt()
```

```{r}
# Here I read in all the CDC data for Chlamydia and Gonorrhea rates from 2000 to
# 2017. I still should rename the columns so that it is clear which values are
# for which variable when I join the datasets. Also, for testing pursposes, I
# have set this to only return the first ten rows as it is a large dataset.

# year is not in numbe=[]

chlamydia_gonorrhea <-read_xlsx("Data_Sets/CDC_Data/ATLAS_CDC_Chlamydia&Gonorrhea.xlsx",
  skip = 5) %>% 
  clean_names() 
chlamydia_gonorrhea[chlamydia_gonorrhea == "Data not available"] <-NA

chlamydia_gonorrhea <- chlamydia_gonorrhea %>% 
  slice(1:10) 

chlamydia_gonorrhea

```

```{r}
# Here I read in all the CDC data for HIV/AIDS rates for females from 2008 to
# 2017. I have added an extra column to list what the sex is.

hiv_aids_f <- read_xlsx("Data_Sets/CDC_Data/Atlas_CDC_HIV:AIDS_Female.xlsx",
  skip = 8) %>% 
  clean_names() %>% 
  mutate(sex = "F")
hiv_aids_f[hiv_aids_f == "Data not available"] <-NA

hiv_aids_f
```

```{r}
# Here I read in all the CDC data for HIV/AIDS rates for males from 2008 to
# 2017. I have added an extra column to list what the sex is.

hiv_aids_m <- read_xlsx("Data_Sets/CDC_Data/AtlasPlus_CDC_Male_HIV:AIDS.xlsx",
  skip = 8) %>% 
  clean_names() %>% 
  mutate(sex = "M")
hiv_aids_m[hiv_aids_m == "Data not available"] <-NA

hiv_aids_m

```

```{r}
# Here I merged the two HIV/AIDS datasets as the variables were the same for
# both the female and male tables. For testing purposes, I am only showing the
# first 10 rows.

hiv_aids_all <- rbind(hiv_aids_f, hiv_aids_m) %>%
  slice(1:10) %>% 
  gt()

hiv_aids_all
```


```{r}
# Here I read in all the CDC data for both early latent and congential syphilis
# rates from 2008 to 2017. I still should rename the columns so that it is clear
# which values are for which variable when I join the datasets.

syphilis <- read_xlsx("Data_Sets/CDC_Data/Atlas_Congenital&EarlyLatentSyphilis.xlsx",
  skip = 7) %>% 
  clean_names()
syphilis[syphilis == "Data not available"] <-NA

syphilis <- syphilis %>% 
  gt()

syphilis
```

```{r}
# How should I combine the data? with a bind or with a join?
```

