---
title: "Graphs"
author: "John Morse"
date: "3/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, include = FALSE}
library(readxl)
library(janitor)
library(tidyverse)
library(gt)
library(rvest)
library(reprex)
library(fivethirtyeight)
```

```{r, include = FALSE}
# PREP DATA

# Empty data set where I will store the files once they'e loaded in.
prep_data_1 <- data.frame()

# Listing out all the files in this particular folder. All of this data relates
# to PrEP usage in the U.S..
list <- list.files("Data_Sets/PrEP_Data")

# Here I have the actual function which is picking up on every document that
# ends in ".xlsx" in the "PrEP_Data" folder. The function reads in all of the
# data, and then spits each one into the empty dataframe that I have created.
# Each row is appended onto the preceding year's data.

listxlsx <- dir(pattern = "*.xlsx")
for (i in 1:length(list)){
  print(list[i])
  temp_data <- read_xlsx(paste("Data_Sets/PrEP_Data/",
                               list[i], sep = ""),
                         skip = 1) %>% 
    clean_names()
  
  prep_data_1 = rbind(prep_data_1, temp_data)
}
```


```{r}
# PrEP growth rates for men and women

# data for only male users
prep_m <- prep_data_1 %>% 
  select(year, male_pr_ep_users, male_pr_ep_rate) %>%
  mutate(sex = "Male")
colnames(prep_m)[2:3] <- c("pr_ep_users", "pr_ep_rate")

# data for only female users
prep_f <- prep_data_1 %>% 
  select(year, female_pr_ep_users, female_pr_ep_rate) %>% 
  mutate(sex = "Female")
colnames(prep_f)[2:3] <- c("pr_ep_users", "pr_ep_rate")

# Here I'll use the bind function to list the information ontop of eachother,
prep_gender = rbind(prep_f, prep_m)

ggplot(data = prep_gender, aes(x = year, y = pr_ep_users, fill = sex)) +
  geom_col(position = "dodge") +
  labs(title="PrEP Users by Gender", subtitle = "2012-2018") +
  theme_classic() +
  scale_x_continuous(
    name = "Year",
  breaks = seq(2012,2018,1),
  label = c("2012", "2013", "2014", "2015", "2016","2017","2018")) +
  scale_y_continuous(
    name = "PrEP Users"
  )
ggsave("image1.jpeg",
       path = "shiny")
```

```{r HIV DIAGNOSIS ONLY, include = FALSE}
# Here I read in all the CDC data for HIV/AIDS rates for females from 2008 to
# 2017. I have added an extra column to list what the sex is.

hiv_aids_f <- read_xlsx("Data_Sets/CDC_Data/Atlas_CDC_HIV:AIDS_Female.xlsx",
  skip = 8) %>% 
  clean_names() %>% 
  mutate(sex = "F")
hiv_aids_f[hiv_aids_f == "Data not available"] <-NA

# Here I read in all the CDC data for HIV/AIDS rates for males from 2008 to
# 2017. I have added an extra column to list what the sex is.

hiv_aids_m <- read_xlsx("Data_Sets/CDC_Data/AtlasPlus_CDC_Male_HIV:AIDS.xlsx",
  skip = 8) %>% 
  clean_names() %>% 
  mutate(sex = "M")
hiv_aids_m[hiv_aids_m == "Data not available"] <-NA

# Here I merged the two HIV/AIDS datasets as the variables were the same for
# both the female and male tables. For testing purposes, I am only showing the
# first 10 rows.

# I filtered for indicator of HIV diagnoses because if I do not, it lumps prevelance and diagnoses together in a way that is misleading for the information I want to communicate.

hiv_aids_all <- rbind(hiv_aids_f, hiv_aids_m) %>% 
  filter(indicator == "HIV diagnoses")

hiv_aids_all_test <- hiv_aids_all %>%
  slice(1:10) %>% 
  gt()

```


```{r HIV Cases by year Graph}

hiv_aids_year <- hiv_aids_all %>% 
  group_by(year) %>%
  summarize(total_cases = sum(cases))

 ggplot(hiv_aids_year, aes(x = year, y = total_cases)) +
   geom_point() +
   geom_text(aes(x = year, y = total_cases, label = total_cases),vjust = -1, nudge_y = .5) +
   labs(title="HIV Diagnoses by Year", subtitle = "2007-2017") +
   theme_classic() +
   scale_x_continuous(
     name = "Year",
     breaks = seq(2007,2017,1),
     label = c("2007", "2008", "2009", "2010", "2011","2012","2013","2014","2015","2016","2017")) +
   scale_y_continuous(
     name = "New Diagnoses",
     limits=c(35000, 50000))

 ggsave("image2.jpeg",
       path = "shiny")
```

```{r HIV Diagnoses by Gender Graph}

ggplot(data = hiv_aids_all, aes(x = year, y = cases, fill = sex)) +
  geom_col(position = "dodge") +
  labs(title="HIV Diagnoses by Gender", subtitle = "2007-2017") +
  theme_classic() +
  scale_x_continuous(
    name = "Year",
    breaks = seq(2007,2017,1),
    label = c("2007", "2008", "2009", "2010", "2011","2012","2013","2014","2015","2016","2017")) +
  scale_y_continuous(
    name = "New Diagnoses"
  )

ggsave("image3.jpeg",
       path = "shiny")
```

```{r HIV Diagnoses Transmission Category Tibble, include = FALSE}
hiv_aids_transmission <- hiv_aids_all %>% 
  group_by(transmission_category, year, sex) %>%
  summarize(total_cases = sum(cases))
hiv_aids_transmission
```

```{r HIV Diagnosis by Category Graph}
ggplot(data = hiv_aids_transmission, aes(x = year, y = total_cases, fill = transmission_category)) +
  geom_col(position = "dodge") +
  labs(title="HIV Diagnosis by Category", subtitle = "2007-2017") +
  theme_classic() +
  scale_x_continuous(
    name = "Year",
   breaks = seq(2007,2017,2),
    label = c("'07", "'09", "'11", "'13", "'15","'17")) +
  scale_y_continuous(
    name = "New Diagnoses"
  )

ggsave("image4.jpeg",
       path = "shiny")
```


```{r Male to male sexual contact(facet_wrap)}
ggplot(data = hiv_aids_maletomalesexualcontact, aes(x = year, y = total_cases, fill = race_ethnicity)) +
  geom_col() +
  facet_wrap(~ race_ethnicity) +
  labs(title="HIV Diagnosis Male-to-male Sexual Contact", subtitle = "2007-2017") +
  theme_classic() +
  scale_x_continuous(
    name = "Year",
    breaks = seq(2007,2017,2),
    label = c("'07", "'09", "'11", "'13", "'15","'17")) +
  scale_y_continuous(
    name = "New Diagnoses"
  )

ggsave("image5.jpeg",
       path = "shiny")
```

